### ISSUE TITLE
windows package

### ISSUE THREAD

**Issue by btel** [conda-forge/python-confluent-kafka-feedstock#39]
Currently there is no windows package in conda-forge channel. Is it planned?

- [ x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by dopplershift** [comment]
Fixed by #40 awhile ago.
